name: test new release

on:
  pull_request:
    branches: develop

jobs:
  testing_release:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name:  ECR Image Tag Check
        id: image_tag
        run: |
          echo "image=$(aws ecr-public describe-image-tags --repository-name reancare --region us-east-1 --query "imageTagDetails[?imageTag=='97777323'].imageTag" --output text)" >> $GITHUB_OUTPUT
        shell: bash
       
      - name: testing image
        run: echo ${#'${{ steps.image_tag.outputs.image }}'}
        
        
#       - name: ECR Image Tag Check
#         run: |
#           if [ ${{ steps.image_tag.outputs.image }} ==  ]; then exit 1; fi
