name: testing release of prod

on:
  # Triggers the workflow on push events but only for the develop branch
  pull_request:
    branches: [feature/aha_fix]

jobs:
  
  Github-ECR-Tag-Check:
    runs-on: ubuntu-latest
    
    steps:
      - name: check tag
        uses: mukunku/tag-exists-action@v1.2.0
        id: checkTag
        with: 
          tag: v32.1.0
      - name: echo tag
        run: echo ${{ steps.checkTag.outputs.exists }} 
      
#       - name: Get release
#         if: ${{ steps.checkTag.outputs.exists == 'true' }}
#         id: result_release
#         uses: cardinalby/git-get-release-action@v1
#         env:
#          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
#         with:
#            tag: ${{ github.event.inputs.Tag_name }}
#            repo: REAN-Foundation/reancare-service
           
#       - name: Configure AWS credentials
#         if: ${{ steps.checkTag.outputs.exists == 'true' }}
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ secrets.AWS_REGION }}
          
#       - name:  Get ECR Image Tag
#         if: ${{ steps.checkTag.outputs.exists == 'true' }}
#         id: imageidvar
#         run: |
#           image_tag+=${{ steps.result_release.outputs.tag_name }} && image_tag+=_ && image_tag+=${{ steps.result_release.outputs.id }}
#           echo "imagetag_value=$(aws ecr-public describe-image-tags --repository-name reancare --region us-east-1 --query "imageTagDetails[?imageTag=='$image_tag'].imageTag" --output text)" >> $GITHUB_OUTPUT
            
#       - name: ECR Image Tag Check
#         if: ${{ steps.checkTag.outputs.exists == 'true' }}
#         run: |
#           if [[ -z "${{ steps.imageidvar.outputs.imagetag_value }}" ]]; then exit 1; fi
    
#     outputs:
#       release_name: ${{ steps.result_release.outputs.tag_name }}
#       release_id: ${{ steps.result_release.outputs.id }}
