name: testing

on:
  pull_request:
    branches: develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}
      
        - name:  list images
          run: aws ecr-public list-tags-for-resource --resource-arn arn:aws:ecr::public.ecr.aws/i9y2d4u3/reancare
#           run: aws ecr-public describe-images --repository-name reancare --region us-east-1
#           run: aws ecr-public describe-repositories --region us-east-1
          shell: bash
