name: testing

on:
  pull_request:
    branches: develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}
      
        - name:  list images
          run: IMAGE_META="$( aws ecr-public describe-image-tags --repository-name reancare --region us-east-1 --query "imageTagDetails[?imageTag=='v33.0.0_97362532'].imageTag" --output text )" echo $IMAGE_META
#           run: aws ecr-public describe-repositories --region us-east-1
          shell: bash
        - name: testing
          run: echo $IMAGE_META
