name: test new release

on:
  pull_request:
    branches: develop

jobs:
  testing_release:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name:  Get ECR Image Tag
        id: image_id
        run: |
          tag=v33.0.1
          echo $tag
          id=97362866
          echo $id
          tag_image= $tag_$id
          echo $tag_image
          
          
#       - name: ECR Image Tag Check
# #         run: |
#             echo "image_tag=$(aws ecr-public describe-image-tags --repository-name reancare --region us-east-1 --query "imageTagDetails[?imageTag=='$tag_$id'].imageTag" --output text)" >> $GITHUB_OUTPUT

# #           if [[ -z "${{ steps.image_id.outputs.image_tag }}" ]]; then exit 1; fi
