name: testing 

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the develop branch
  pull_request:
#     inputs:
#       Tag_name:
#         description: Tag name of your release
#         default: 31.1.0
#         required: true
        
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    
      - name: Get release
        id: result_release
        uses: cardinalby/git-get-release-action@v1
        env:
         GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
        with:
           tag: v31.0.0
           repo: REAN-Foundation/reancare-service
