name: testing

on:
  pull_request:
    branches: develop

jobs:
  Github-ECR-Tag-Check:
    runs-on: ubuntu-latest
    
    steps:
      - name: check tag
        uses: mukunku/tag-exists-action@v1.2.0
        id: checkTag
        with: 
          tag: v32.0.0
      
#       - name: Get release
#         if: ${{ steps.checkTag.outputs.exists == 'true' }}
#         id: result_release
#         uses: cardinalby/git-get-release-action@v1
#         env:
#          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
#         with:
#            tag: v32.0.0
#            repo: REAN-Foundation/reancare-service
       
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name:  ECR Image Tag Check
        run: |
          sudo mkdir /home/image_meta/
          cd /home/image_meta/
          aws ecr-public describe-image-tags --repository-name reancare --region us-east-1 --query "imageTagDetails[?imageTag=='97776691'].imageTag" --output text >> ./image_tag.txt
          IMAGE_TAG=`cat ./image_tag.txt`
          if [ '97776691' != $IMAGE_TAG ]; then exit 1; fi
        shell: bash








#   test:
#     runs-on: ubuntu-latest
#     steps:
          
#         - name: Configure AWS credentials
#           uses: aws-actions/configure-aws-credentials@v1
#           with:
#             aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#             aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#             aws-region: ${{ secrets.AWS_REGION }}
        
#         - name: check tag
#           uses: mukunku/tag-exists-action@v1.2.0
#           id: checkTag
#           with: 
#             tag: v7.0.1
      
#         - name:  list images
#           run: |
#             sudo mkdir /home/image_meta/
#             cd /home/image_meta/
#             aws ecr-public describe-image-tags --repository-name reancare --region us-east-1 --query "imageTagDetails[?imageTag=='v33.0.0_97362532'].imageTag" --output text >> ./image_tag.txt
#             IMAGE_TAG=`cat ./image_tag.txt`
#           shell: bash
          
#         - name: Github Tag and ECR image Tag Check
#           run: |
#             if [ ${{ steps.checkTag.outputs.exists }} == false ]; then exit 1; fi
#             if [ ${{ steps.checkTag.outputs.exists }} == '' ]; then exit 1; fi
